### ISSUE TITLE
Reconfirm Hero Talent Selection

### ISSUE THREAD

**Issue by edge-blade** [edge-blade/Dota-2-AI-Bot-Experiment#14]
Item builds were updated, but talent selection probably needs to be tweaked on quite a few heroes as well.

**Comment by RickyJuno** [comment]
### Please forgive me for the wall I'm posting here.
### I swear to god if they update all the talents tomorrow or something I will riot.

**Abaddon:**
10 talent left (+8 strength)
15 talent left (+50 mist coil heal/damage)
20 talent right (+100 aphotic shield health)
25 talent left (+400 mist coil aoe)

**Alchemist:**
10 talent left (+125 unstable concontion radius)
15 talent right (+350 health)
20 talent right (+25% cleave)
25 talent left (+50 chemical rage regeneration)

**Ancient Apparition:**
10 talent left (+8% spell amp)
15 talent left (+200 cold feet break distance)
20 talent right (-5% ice vortex slow/resist)
25 talent right (+450 aoe cold feet)

**Anti-Mage:**
10 talent right (+9 strength)
15 talent right (+0.6% max mana mana break)
20 talent right (+0.1 mana void damage)
25 talent right (+20% counterspell magic resist)

**Arc Warden:**
10 talent right (+175 flux cast range)
15 talent right (+2s flux duration)
20 talent right (+125 spark wraith damage)
25 talent left (+12s tempest double duration)

**Axe:**
10 talent right (+1.5 mana regen)
15 talent right (10% battle hunger slow)
20 talent left (+1 armor per culling blade) _Note: Not sure the AI will factor in the right side talent of +150 culling blade damage, so I am choosing to skip the right side 20 here to prevent issues later on down the road, despite it being better_
25 talent right (+100 berserker's call aoe)

**Bane:**
10 talent right (+5 armor)
15 talent right (-3 sec brain sap cooldown)
20 talent left (+30 movespeed)
25 talent left (+5 sec fiend's grip)

**Batrider:**
10 talent right (+75 napalm radius)
15 talent left (-10s lasso cooldown)
20 talent right (+6 stick napalm damage) _Note: not sure how AI will treat having 2 charges on an ability suddenly, so leaning towards the more AI-friendly talent_
25 talent left (flamebreak applies 2 napalm)

**Beastmaster:**
10 talent right (+30 damage)
15 talent right (+25 unit movespeed)
20 talent left (+250 unit health)
25 talent left (-30s roar cooldown)

**Bloodseeker:**
10 talent right (+30 bloodrage AS)
15 talent right (+10% rupture initial damage)
20 talent right (+475 rupture cast range)
25 talent left (+14% max thirst MS)  _Note: not sure how AI will treat having 2 charges on an ability suddenly, so leaning towards the more AI-friendly talent_

**Bounty Hunter:**
10 talent left (+40 jinada damage)
15 talent left (half track ms to allies)
20 talent right (track grants 600 ground vision)
25 talent left (+250 track gold) _Note: not sure how AI will treat having 2 charges on an ability suddenly, so leaning towards the more AI-friendly talent_

**Brewmaster:**
10 talent left (+200 thunder clap aoe)
15 talent right (+30% cinder brew damage/duration)
20 talent right (+1400 brewling health)
25 talent right (brewlings gain drunken brawler)

**Bristleback:**
10 talent right (+15 damage)
15 talent right (+200 health)
20 talent right (+20 health regen)
25 talent left (+25 warpath damage per stack)

**Broodmother:**
10 talent left (+3 spin webs)
15 talent right (-10s spin web recharge)
20 talent left (+400 health)
25 talent left (+350 spiderling health)

**Centaur Warrunner:**
10 talent right (+5 health regen)
15 talent right (+15 strength)
20 talent right (+45 retaliate damage)
25 talent right (retaliate aura)

**Chaos Knight:**
10 talent right (+20% chaos strike lifesteal)
15 talent right (-3s chaos bolt cooldown)
20 talent right (0.5s min/max chaos bolt)
25 talent left (+10s phantasm duration)

**Chen:**
10 talent left (+200 health)
15 talent right (+16 creep damage)
20 talent right (-40s hand of god cooldown)
25 talent left (+10/+10 hand of god healing)

**Clinkz:**
10 talent right (+20 searing arrows)
15 talent right (+25% death pact health)
20 talent right (+125 attack range)
25 talent left (searing arrows multishot)

**Clockwerk:**
10 talent right (-2 rocket flare cooldown)
15 talent right (+2 hits to kill cogs)
20 talent right (rocket flare true sight)
25 talent left (0.25 battery assault interval)

**Crystal Maiden:**
10 talent right (+250 health)
15 talent right (+20 arcane aura cast mana)
20 talent left (+50 freezing field damage)
25 talent left (+240 crystal nova damage)

**Dark Seer:**
10 talent right (+20% wall illusion damage)
15 talent right (+100 vacuum aoe)
20 talent left (+50 ion shell dps)
25 talent left (350 aoe surge) _Note: no clue how the bot will handle parallel walls.

**Dark Willow:**
10 talent right (+0.5s cursed crown stun)
15 talent right (+30 bedlam damage)
20 talent right (+2s shadow realm duration)
25 talent left (+1.5s terrorize duration)

**Dawnbreaker:**
10 talent right (+25 starbreaker damage)
15 talent right (+50% luminosity crit)
20 talent right (+150 solar guardian radius)
25 talent left (+1100 celestial hammer range) _Note: not sure how AI will treat having 2 charges on an ability suddenly, so leaning towards the more AI-friendly talent_

**Dazzle:**
10 talent left (+1.75 mana regen)
15 talent right (+50 shadow wave heal/damage)
20 talent right (+250 heal on shallow grave end)
25 talent left (+0.5 bad juju armor)

**Death Prophet:**
10 talent left (+12% magic resistance)
15 talent right (+1% max health spirit siphon)
20 talent right (20% spirit siphon move speed)
25 talent right (-20s spirit siphon charge time)

**Disruptor:**
10 talent right (-3s kinetic field cooldown)
15 talent left (+2s static storm duration)
20 talent right (+2s kinetic field duration)
25 talent left (+250 static storm aoe)

**Doom:**
10 talent right (+12% magic resist)
15 talent right (-8s scorched earth cooldown)
20 talent left (+15% scorched earth speed)
25 talent right (+2.1% infernal blade damage)

**Dragon Knight:**
10 talent right (+15 damage)
15 talent right (+0.5 dragon tail stun)
20 talent right (+175 dragon form range)
25 talent right (+12 dragon blood)

**Drow Ranger:**
10 talent right (+50% gust blind)
15 talent right (+250 gust width)
20 talent right (+28% multishot damage)
25 talent right (+12% marksmanship chance)

**Earth Spirit:**
10 talent right (+325 roll range)
15 talent left (+120 roll damage)
20 talent right (+18% spell amp)
25 talent left (+0.6 roll stun)

**Earthshaker:**
10 talent right (+30 base damage)
15 talent right (+50% enchant totem damage)
20 talent left (+320 fissure range)
25 talent right (+200 aftershock range)

**Elder Titan:**
10 talent right (+2% spirit move speed)
15 talent right (+15% magic resistance)
20 talent left (+100 echo stomp damage)
25 talent left (+450 echo stomp wake damage)

**Ember Spirit:**
10 talent right (+15 damage)
15 talent left (+1s searing chains duration)
20 talent right (+1 searing chains target)
25 talent left (-12 remnant charge time) _Note: not sure how AI will treat having 2 charges on an ability suddenly, so leaning towards the more AI-friendly talent_

**Enchantress:**
10 talent right (+10% magic resist)
15 talent left (+5 wisps)
20 talent right (-65 untouchable slow) _Note: do not know how the AI will handle controlling ancient units
25 talent left (+20 wisp heal)

**Enigma:**
10 talent right (+20 eidolon attack speed)
15 talent right (+200 midnight pulse radius)
20 talent right (+400 health)
25 talent left (+5 eidolons)

**Faceless Void:**
10 talent left (+0.5s time walk backtrack)
15 talent right (-1.5s time walk cooldown)
20 talent right (+120 attack speed during chrono)
25 talent right (+20% backtrack)

**Grimstroke:**
10 talent right (+50 phantom dps)
15 talent left (+16% ink swell speed)
20 talent left (+3 hits to kill phantom)
25 talent right (+150 ink swell radius)

**Gyrocopter:**
10 talent left (+200 health)
15 talent right (+0.4s missile stun)
20 talent left (+16 barrage damage)
25 talent right (-6s flak cannon cooldown)

**Hoodwink:**
10 talent left (-4s bushwhack cooldown)
15 talent left (+2 acorn shot bounces) _Note: Scurry camouflage will either never trigger or confuse the bot when it does trigger.
20 talent right (25% sharpshooter speed)
25 talent left (+135 bushwhack radius)

**Huskar:**
10 talent right (+1s inner fire duration)
15 talent right (+4 burning spear dps)
20 talent right (+30% berserker's regen)
25 talent left (burning spear pure damage)

**Invoker:**
_Note: Invoker usually doesn't take talents when available and instead waits on them. Below is which talent to take, but not necessarily at the level it should be taken_
10 talent left (+40% chaos meteor damage)
15 talent right (+50 forged spirit attack speed)
20 talent left (+30 alacrity damage/speed)
25 talent right (radial deafening blast)

**Io:**
10 talent right (+4 health regen)
15 talent right (+6% tether speed)
20 talent right (+0.2% overcharge bonus)
25 talent left (Attack tethered ally's target)

**Jakiro:**
10 talent right (+325 attack range)
15 talent left (+325 health)
20 talent right (+0.5 ice path duration)
25 talent right (2x dual breath damage/range)

**Juggernaut:**
10 talent right (+5 all stats)
15 talent right (-20s healing ward cooldown)
20 talent right (+40% crit lifesteal)
25 talent right (+475 health)

**Keeper of the Light:**
10 talent right (+30% blinding light blind)
15 talent right (-4s chakra cooldown)
20 talent right (+15s spirit form duration)
25 talent left (+180 illuminate damage)

**Kunkka:**
10 talent right (+30 damage)
15 talent left (+100 torrent damage)
20 talent left (+70% tidebringer cleave)
25 talent left (-2s tidebringer cooldown)

**Legion Commander:**
10 talent right (+100 overwhelming odds radius)
15 talent right (+40 press the attack regen)
20 talent right (+250 press the attack aoe)
25 talent right (+30 duel damage)

**Leshrac:**
10 talent right (+1.75 mana regen)
15 talent right (+100 lightning storm damage)
20 talent left (+40 pulse nova damage)
25 talent left (+30 edict explosions)

**Lich:**
10 talent left (+125 blast radius/damage)
15 talent right (+0.5s sinister gaze)
20 talent right (+100 chain frost damage)
25 talent left (unlimited bounces)

**Lifestealer:**
10 talent right (+30 attack speed)
15 talent right (+25 damage)
20 talent left (+10% ghoul frenzy slow)
25 talent right (+1.2% feast lifesteal)

**Lina:**
_Note: the most successful talents seem to lean towards a support Lina build, her skill build might have to change to accommodate_
10 talent right (+25 damage)
15 talent right (+350 health)
20 talent right (+11% spell amp)
25 talent right (-25s Laguna blade cooldown)

**Lion:**
10 talent right (+15 movement speed)
15 talent right (-2s earth spike cooldown)
20 talent right (+20 finger damage/kill) _Note: Mana Drain Restores Allies does not seem very bot-friendly, so it is being skipped
25 talent right (+800 earth spike range)

**Lone Druid:**
10 talent right (+200 health)
15 talent right (-8s savage roar cooldown)
20 talent left (0 entangling claws cooldown)
25 talent right (0.1 bear attack time)

**Luna:**
10 talent right (-8% glaive damage)
15 talent right (-3s lucent beam cooldown)
20 talent right (lunar blessing global)
25 talent right (+35 lunar blessing damage)

**Lycan:**
10 talent left (+10 wolf damage)
15 talent right (+200 wolf health)
20 talent left (+25% feral impulse)
25 talent left (+2 wolves)

**Magnus:**
10 talent right (+10% empower duration)
15 talent right (+12 strength)
20 talent right (+125 shockwave damage)
25 talent right (+10% empower damage/cleave)

**Marci:**
10 talent right (+5 armor)
15 talent left (+200 round cast/jump range)
20 talent left (+30 movespeed)
25 talent left (+1.5s sidekick spell immunity)

**Mars:**
10 talent right (+1.5s Rebuke slow)
15 talent right (-4s Rebuke cooldown)
20 talent right (+10%/+5% Bulwark)
25 talent left (Arena grants team +180 regen)

**Medusa:**
10 talent right (+20 attack speed)
15 talent right (+12% split shot damage)
20 talent right (+2 mystic snake bounces)
25 talent right (+75 inteligence)

**Meepo:**
10 talent right (+6 strength)
15 talent right (+15% evasion)
20 talent left (+8 ransack health steal)
25 talent left (+1 Meepo)

**Mirana:**
10 talent right (-2 sacred arrow cooldown)
15 talent right (moonlight shadow gives 20% evasion)
20 talent right (-20s moonlight shadow cooldown)
25 talent right (+2 multishot sacred arrows)

**Monkey King:**
10 talent right (+50% tree dance vision)
15 talent right (+450 tree dance cast range)
20 talent left (-7s boundless strike cooldown) _Note: not sure how AI will treat having 2 charges on an ability suddenly, so leaning towards the more AI-friendly talent_
25 talent right (0 cooldown primal spring)

**Morphling:**
10 talent right (+15% magic resist)
15 talent left (+15 agility)
20 talent right (+20 strength)
25 talent left (shift while stunned) _Note: not sure how AI will treat having 2 charges on an ability suddenly, so leaning towards the more AI-friendly talent_

**Naga Siren:**
10 talent right (+20 movespeed)
15 talent right (+13% mirror image damage)
20 talent right (-1 rip tide hits)
25 talent right (-10s mirror image cooldown)

**Nature's Prophet:**
10 talent right (-8s nature's call cooldown)
15 talent left (+5 treants)
20 talent right (sprout leashes)
25 talent left (2.5x treant HP/damage)

**Necrophos:**
10 talent right (+100 scythe cast range)
15 talent right (+24% shroud slow)
20 talent right (+15% magic resist)
25 talent Left (-2.5s death pulse cooldown)

**Night Stalker:**
10 talent right (+50 void damage)
15 talent right (+35 dark ascension damage)
20 talent right (-5s crippling fear cooldown)
25 talent right (+100 hunter in the night attack speed)

**Nyx Assassin:**
10 talent right (+8% spell amp)
15 talent right (+250 health)
20 talent right (+0.6s carapace stun)
25 talent left (Vendetta unobstructed pathing)

**Ogre Magi:**
10 talent right (+16 ignite dps)
15 talent left (+250 health)
20 talent left (+25 bloodlust attack speed)
25 talent left (+240 fireblast damage)

**Omniknight:**
10 talent right (+4s heavenly grace duration)
15 talent left (-30s guardian angel cooldown)
20 talent right (+4 heavenly grace strength/regen)
25 talent right (+160 purification damage/heal)

**Oracle:**
10 talent right (+0.4s fortune's end duration)
15 talent left (-1.25 purifying flames cooldown)
20 talent right (-20s false promise cooldown)
25 talent left (+1.5s false promise duration)

**Outworld Destroyer:*
10 talent right (+200 health)
15 talent right (+250 mana)
20 talent right (+20 strength)
25 talent right (+2% arcane orb damage)

**Pangolier:**
10 talent right (+1.5 mana regen)
15 talent right (2.5 shield crash CD)
20 talent right (+20 swashbuckle damage)
25 talent right (3s swashbuckle cooldown)

**Phantom Assassin:**
10 talent right (+1s phantom strike duration)
15 talent right (+15% lifesteal)
20 talent right (+20% dagger damage)
25 talent right (+7% coup de grace chance)

**Phantom Lancer:**
10 talent right (+150 health)
15 talent right (+15 strength)
20 talent right (+300 phantom rush range)
25 talent right (-4s doppelganger cooldown)

**Phoenix:**
10 talent right (+25% dive slow)
15 talent right (+25 spirits dps)
20 talent right (+1.5% max health sun ray)
25 talent left (+1000 dive cast range)

**Primal Beast:**
10 talent right (+12% magic resist)
15 talent right (+3 uproar armor per stack)
20 talent right (+25% trample modifier)
25 talent left (50% spell lifesteal)

**Puck:**
10 talent right (-2s Orb cooldown)
15 talent right (-10s Coil cooldown)
20 talent right (-6s rift cooldown)
25 talent left (dream coil rapid fire)

**Pudge:**
10 talent right (+4 armor)
15 talent right (+10% spell lifesteal)
20 talent right (+0.8s dismember duration)
25 talent right (x1.8 dismember damage)

**Pugna:**
10 talent right (+20 movement speed)
15 talent right (-1s netherblast cooldown)
20 talent left (+1s decrepify duriontation) _Note: +20% life drain heal is only when used on allies, which I don't believe Pugna bot does, so that talent is being skipped.
25 talent left (+1.75 ward damage)

**Queen of Pain:**
10 talent right (+20 damage)
15 talent right (+2 show strike instances)
20 talent right (+120 scream damage)
25 talent right (-2s Blink cooldown)

**Razor:**
10 talent right (+30 plasma field damage)
15 talent right (+5 static link steal)
20 talent right (+21% storm surge movespeed)
25 talent right (+80 attack speed)

**Riki:**
10 talent right (+75 smoke screen aoe)
15 talent right (8% cloak and dagger movespeed)
20 talent right (+0.5 backstab multiplier)
25 talent right (-4 tricks of the trade cooldown)

**Rubick:**
10 talent right (+175 telekinesis landing damage)
15 talent right (-25% stolen spells cooldown)
20 talent left (+240 telekinesis land distance)
25 talent left (+40% spell amp for stolen spells)

**Sand King:**
10 talent right (+15 sand storm dps)
15 talent right (+125 sand storm radius)
20 talent right (-2s burrowstrike cooldown)
25 talent left (35% sand storm slow/blind)

**Shadow Demon:**
10 talent left (+10 strength)
15 talent right (+25 movespeed)
20 talent right (-6s soul catcher cooldown)
25 talent right (-30s demonic purge cooldown) _Note: not sure how AI will treat having 2 charges on an ability suddenly, so leaning towards the more AI-friendly talent_

**Shadow Fiend:**
10 talent right (+25 shadowraze stackd amage)
15 talent right (presence aura affects buildings)
20 talent right (+3 damage per soul)
25 talent right (-4 presence aura armor)

**Shadow Shaman:**
10 talent left (-3s hex cooldown)
15 talent left (+1s shackles duration)
20 talent left (+1 ward HP)
25 talent left (+25 ward attack damage)

**Silencer:**
10 talent right (+12 arcane curse damage)
15 talent right (+100 attack range)
20 talent left (+1.2x last word int multiplier)
25 talent right (+15% glaives of wisdom damage)

**Skywrath Mage:**
10 talent right (+175 health)
15 talent right (-8s ancient seal cooldown)
20 talent left (-12% ancient seal magic resist)
25 talent left (+450 Mystic Flare damage)

**Slardar:**
10 talent right (-3s sprint cooldown)
15 talent right (+325 health)
20 talent right (+150 crush damage)
25 talent left (corrosive haze undispellable)

**Slark:**
10 talent right (-1s dark pact cooldown)
15 talent right (+70 dark pact damage)
20 talent right (+1 agility gain/stolen)
25 talent right (+1 shadow dance duration)

**Snapfire:**
10 talent right (+0.3 cookie stun)
15 talent right (+2 lil' shredder attacks)
20 talent left (+20% kisses movement slow)
25 talent left (+6 kisses)

**Sniper:**
10 talent right (1s take aim duration)
15 talent right (+30 attack speed)
20 talent right (+28 headshot knockback)
25 talent right (+100 attack range)

**Spectre:**
10 talent right (-4s dagger cooldown)
15 talent right (+12 desolate damage)
20 talent left (+12% dagger slow)
25 talent right (+32% haunt illusion damage)

**Spirit Breaker:**
10 talent right (+500 night vision)
15 talent right (-4s bulldoze cooldown)
20 talent left (+175 charge speed)
25 talent Right (+25% greater bash chance)

**Storm Spirit:**
10 talent left (+1.5 mana regen)
15 talent right (+250 health)
20 talent right (+0.4s electric vortex)
25 talent right (2x overload bounce)

**Sven:**
10 talent right (+3s warcry duration)
15 talent right (-15s god's strength cooldown)
20 talent right (+8% warcry movement)
25 talent right (+50% god's strength damage)

**Templar Assassin:**
10 talent right (+20 attack speed)
15 talent right (+20% evasion)
20 talent right (Meld dispels)
25 talent left (+7 refraction instances)

**Terrorblade:**
10 talent right (+2s reflection duration)
15 talent right (+300 Health)
20 talent right (+10 all stats)
25 talent left (+20s metamorphosis duration)

**Tidehunter:**
10 talent right (+10% gush slow)
15 talent right (+120 gush damage)
20 talent left (-4 gush armor)
25 talent right (1s ravage stun)

**Timbersaw:**
10 talent right (+200 health)
15 talent right (+8% spell amp)
20 talent right (+16 strength)
25 talent left (+1125 timber chain range)

**Tiny:**
10 talent right (+20 movement speed)
15 talent right (+10% status resistance)
20 talent right (+40% grow bonus damage)
25 talent right (-8s Avalanche cooldown)

**Treant Protector:**
10 talent right (+36 living armor heal)
15 talent right (+15% leech seed slow)
20 talent right (+8 living armor bonus armor)
25 talent left (450 aoe living armor)

**Troll Warlord:**
10 talent right (+7 rage armor)
15 talent right (+5 fervor attack speed)
20 talent left (+30 damage)
25 talent left (battle trance strong dispel)

**Tusk:**
10 talent right (+25 tag team damage)
15 talent right (+325 health)
20 talent right (-6s ice shards cooldown)
25 talent left (-8s snowball cooldown)

**Underlord:**
10 talent right (+5 armor)
15 talent right (+75 pit aoe)
20 talent right (+1% firestorm burn damage)
25 talent left (+50% atrophy aura)

**Undying:**
10 talent left (-15s tombstone cooldown)
15 talent left (+12 soul rip damage/heal)
20 talent right (tombstone on death)
25 talent right (reincarnation 300 CD)

**Ursa:**
10 talent right (+20s fury swipes reset)
15 talent right (+10 agility)
20 talent right (+15% enrage status resist)
25 talent left (+3 overpower attacks)

**Vengeful Spirit:**
10 talent right (+12% magic resist)
15 talent left (-2.75s magic missile cooldown)
20 talent right (+200 magic missile damage)
25 talent left (magic missile pierces spell immunity)

**Venomancer:**
10 talent right (-6 gale coodlown)
15 talent left (-8% poison sting slow)
20 talent left (-1.5s plague ward cooldown)
25 talent left (2.5x plague ward hp/damage)

**Viper:**
10 talent right (+20 attack speed)
15 talent right (+40 nethertoxin min/max damage)
20 talent left (+8% poison attack magic resist)
25 talent left (2x corrosive skin stats)

**Visage:**
10 talent right (-3s grave chill cooldown)
15 talent right (+1.5 armor corruption for familiars)
20 talent left (+30 visage and familiar movespeed)
25 talent left (+1 familiar)

**Void Spirit:**
10 talent right (+1.75 mana regen)
15 talent right (Remnant provides truesight)
20 talent right (+12% spell amp)
25 talent left (dissimilate stun)

**Warlock:**
10 talent left (+2s shadow word duration)
15 talent left (-4s shadow word cooldown)
20 talent left (+25 shadow word damage/heal)
25 talent left (80% magic resist for golem)

**Weaver:**
10 talent right (+50 shukuchi damage)
15 talent right (+20 mana break)
20 talent left (+0.5 swarm armor reduction)
25 talent left (+1 geminate attack)

**Windranger:**
10 talent right (-5% powershot damage reduction) 
15 talent right (-4s windrun cooldown)
20 talent right (+0.8s shackleshot duration)
25 talent left (Focus fire kills advance cooldown 20s)

**Winter Wyvern:**
10 talent right (+25hp/s cold embrace)
15 talent right (+2s arctic burn debuff)
20 talent right (+12% arctic burn slow)
25 talent left (splinter blast 1.5s stun)

**Witch Doctor:**
10 talent right (-25% voodoo restoration mana per second)
15 talent right (+2 cask bounces)
20 talent right (+100 death ward range)
25 talent right (+1.5% max health voodoo restoration)

**Wraith King:**
10 talent right (+20 movespeed)
15 talent right (+0.7s wraithfire stun)
20 talent left (+6 minimum skeletons spawn)
25 talent right (-2s mortal strike cooldown)

**Zeus:**
10 talent right (+1.25 mana regen)
15 talent right (+350 health)
20 talent right (+100 thundergod's wrath damage)
25 talent right (325 aoe lightning bolt)
